# Generated by Django 3.1.2 on 2021-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210908_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='written_language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('GER', 'German'), ('CHZ', 'Chinese'), ('JPN', 'Japanese')], default='EN', help_text='Select a language for this book', max_length=50, verbose_name='Language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
